version: "3.7"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - dotnet-example-data:/var/lib/mysql
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@minPass123"
    ports: 
      - 1433:1433
  
  app: 
    build:
      context: .
      dockerfile: ./API/Dockerfile
      args:
        ENV_NAME: "Development"
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443

volumes:
  dotnet-example-data:
