version: "3.7"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - dotnet-example-data:/var/lib/mysql
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@minPass123"
    ports: 
      - 1433:1433
    networks:
      dotnet-example-network:
        aliases:
          - db
  
  app: 
    build:
      context: .
      dockerfile: ./API/Dockerfile
    environment: 
      ENV_NAME: "Development.Docker"
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    networks:
      dotnet-example-network:
        aliases:
          - app

volumes:
  dotnet-example-data:

networks:
  dotnet-example-network: