version: "3.7"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - dotnet-example-data:/var/lib/mysql
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: ""
    ports: 
      - 1433:1433
  
  app: 
    image: dotnet-example
    depends_on:
      - db
    ports:
      - 80:80

volumes:
  dotnet-example-data:
